function [output] = sliding_window(fishNray_data,windowsize)
%TIME_AVERAGE Summary of this function goes here

if numel(fishNray_data.hpa)<3
    output = [];
else
    fish_cell = num2cell(repmat(fishNray_data.fish_ray(1),[1,numel(fishNray_data.hpa)-2]),1);
    ray_cell = num2cell(repmat(fishNray_data.fish_ray(2),[1,numel(fishNray_data.hpa)-2]),1);
    hpa_cell = num2cell(fishNray_data.hpa(2:end-1),1);
    L_amp_cell = num2cell(repmat(fishNray_data.L_amp,[1,numel(fishNray_data.hpa)-2]),1);
%     L_end_cell = num2cell(repmat(fishNray_data.L_end,[1,numel(fishNray_data.hpa)-2]),1); % longfin
    
    % GEM
    fractionGEM_u_timeave_cell = num2cell(movmean(fishNray_data.fractionGEM_u,windowsize,2,'omitnan','EndPoints','discard'),1);
    fractionGEM_u_20bins_timeave_cell = num2cell(movmean(fishNray_data.fractionGEM_u_20bins,windowsize,2,'omitnan','EndPoints','discard'),1);

    nucleiALL_u_timeave = movsum(fishNray_data.nucleiALL_u,windowsize,2,'omitnan','EndPoints','discard');
    nucleiALL_u_timeave_cell = num2cell(nucleiALL_u_timeave,1);
    nucleiGEM_u_timeave = movsum(fishNray_data.nucleiGEM_u,windowsize,2,'omitnan','EndPoints','discard');
    nucleiGEM_u_timeave_cell = num2cell(nucleiGEM_u_timeave,1);
    fractionGEM_u_timeresum_cell = num2cell(nucleiGEM_u_timeave./nucleiALL_u_timeave,1);
    
    % ERK
    averageKTR_u_timeave_cell = num2cell(movmean(fishNray_data.averageKTR_u,windowsize,2,'omitnan','EndPoints','discard'),1);
    averageKTR_u_20bins_timeave_cell = num2cell(movmean(fishNray_data.averageKTR_u_20bins,windowsize,2,'omitnan','EndPoints','discard'),1);
    averageKTR_u_bin10_offsetE0_timeave_cell = num2cell(movmean(fishNray_data.averageKTR_u_bin10_offsetE0,windowsize,2,'omitnan','EndPoints','discard'),1);

    hpaTrue_timeave_cell = num2cell(movmean(fishNray_data.hpaTrue,windowsize,2,'omitnan','EndPoints','discard'),1);
    L_reg_timeave_cell = num2cell(movmean(fishNray_data.L_reg,windowsize,2,'omitnan','EndPoints','discard'),1);
    dLdt_timeave_deriv_cell = num2cell(find_derivative(fishNray_data.hpaTrue,fishNray_data.L_reg,cell2mat(hpaTrue_timeave_cell)),1);
    
    % gem_cell, u_cell fixed windowsize = 3
    gem_cell = cellfun(@(x,y,z)cat(1,x,y,z),...
        fishNray_data.gem(1:end-2),fishNray_data.gem(2:end-1),fishNray_data.gem(3:end),...
        'uni',0);
    ktr_cell = cellfun(@(x,y,z)cat(1,x,y,z),...
        fishNray_data.ktr(1:end-2),fishNray_data.ktr(2:end-1),fishNray_data.ktr(3:end),...
        'uni',0);
    u_cell = cellfun(@(x,y,z)cat(1,x,y,z),...
        fishNray_data.u(1:end-2),fishNray_data.u(2:end-1),fishNray_data.u(3:end),...
        'uni',0);
    
    % ERK re-aggregate
    averageKTR_u_timeresum_cell = cellfun(@(c1,c2)...
        bin_average(c1,c2,10,0,1),...
        u_cell,ktr_cell,'UniformOutput',false);


    % append output
    output = struct('fish',fish_cell,...
        'ray', ray_cell, ...
        'hpa', hpa_cell, ...
        'L_amp', L_amp_cell, ...
        'nucleiALL_u_timeave', nucleiALL_u_timeave_cell, ...
        'nucleiGEM_u_timeave', nucleiGEM_u_timeave_cell, ...
        'fractionGEM_u_timeave', fractionGEM_u_timeave_cell, ...
        'fractionGEM_u_20bins_timeave', fractionGEM_u_20bins_timeave_cell,...
        'fractionGEM_u_timeresum', fractionGEM_u_timeresum_cell, ...
        'averageKTR_u_timeave',averageKTR_u_timeave_cell, ...
        'averageKTR_u_20bins_timeave',averageKTR_u_20bins_timeave_cell, ...
        'averageKTR_u_bin10_offsetE0_timeave',averageKTR_u_bin10_offsetE0_timeave_cell,...
        'averageKTR_u_timeresum', averageKTR_u_timeresum_cell,...
        'hpaTrue_timeave', hpaTrue_timeave_cell, ...
        'L_reg_timeave',L_reg_timeave_cell, ...
        'dLdt_timeave_deriv',dLdt_timeave_deriv_cell,...
        'gem', gem_cell, ...
        'ktr', ktr_cell, ...
        'u', u_cell);

%             'L_end', L_end_cell, ...   % for longfin

end







end

